language: python

services:
    - docker

before_install:
    - docker pull cfusting/conditional-growth

script:
    - docker run cfusting/conditional-growth pytest --ignore=tests/test_voxenv.py --ignore=tests/test_plotting.py
