language: python

services:
    - docker

before_install:
    - docker build -t growth .
    - docker run growth pytest --ignore=tests/test_voxenv.py --ignore=tests/test_plotting.py

script:
    - pytest --ignore=tests/test_voxenv.py --ignore=tests/test_plotting.py
